package io.github.lihanc940.openpulse.integration.github;

public enum GithubArchiveFailure {
    INVALID_REPOSITORY_METADATA,
    TEMPORARY_DIRECTORY_CREATION_FAILED,
    ARCHIVE_WRITE_FAILED,
    AUTHENTICATION_FAILED,
    REPOSITORY_NOT_FOUND_OR_INACCESSIBLE,
    RATE_LIMITED,
    GITHUB_UNAVAILABLE,
    DOWNLOAD_TIMEOUT,
    INTERRUPTED,
    UNTRUSTED_REDIRECT,
    ARCHIVE_TOO_LARGE,
    ARCHIVE_INVALID,
    ARCHIVE_ENTRY_LIMIT_EXCEEDED,
    EXTRACTED_CONTENT_TOO_LARGE,
    UNSAFE_ARCHIVE_ENTRY,
    CLEANUP_FAILED
}
