# Validates a generated analyzer report's protocol shape.
# Usage:
#   cmake -DREPORT=<file> -DEXPECT_PROTOCOL=<1.0|2.0> [-DEXPECT_STATUS=<SUCCESS|...>] -P CheckReport.cmake

if(NOT REPORT)
  message(FATAL_ERROR "REPORT is required")
endif()
if(NOT EXPECT_PROTOCOL)
  message(FATAL_ERROR "EXPECT_PROTOCOL is required")
endif()

file(READ "${REPORT}" REPORT_JSON)

string(JSON PROTOCOL ERROR_VARIABLE PROTOCOL_ERR GET "${REPORT_JSON}" protocolVersion)
if(PROTOCOL_ERR)
  message(FATAL_ERROR "report has no protocolVersion: ${PROTOCOL_ERR}")
endif()
if(NOT PROTOCOL STREQUAL EXPECT_PROTOCOL)
  message(FATAL_ERROR "protocolVersion is ${PROTOCOL}, expected ${EXPECT_PROTOCOL}")
endif()

string(JSON STATUS GET "${REPORT_JSON}" status)
if(DEFINED EXPECT_STATUS AND NOT STATUS STREQUAL EXPECT_STATUS)
  message(FATAL_ERROR "status is ${STATUS}, expected ${EXPECT_STATUS}")
endif()

if(EXPECT_PROTOCOL STREQUAL "1.0")
  # v1 legacy fields must still be present
  foreach(KEY risks quality dependencies)
    string(JSON _VALUE ERROR_VARIABLE _ERR GET "${REPORT_JSON}" ${KEY})
    if(_ERR)
      message(FATAL_ERROR "v1 report missing key ${KEY}: ${_ERR}")
    endif()
  endforeach()
else()
  # v2 required top-level keys
  foreach(KEY taskId analyzer ruleSet reviewability repository findings limitations generatedAt)
    string(JSON _VALUE ERROR_VARIABLE _ERR GET "${REPORT_JSON}" ${KEY})
    if(_ERR)
      message(FATAL_ERROR "v2 report missing key ${KEY}: ${_ERR}")
    endif()
  endforeach()

  # v1-only fields must be gone
  foreach(KEY risks quality dependencies)
    string(JSON _VALUE ERROR_VARIABLE _ERR GET "${REPORT_JSON}" ${KEY})
    if(NOT _ERR)
      message(FATAL_ERROR "v2 report must not contain v1 key ${KEY}")
    endif()
  endforeach()

  string(JSON ANALYZER_NAME GET "${REPORT_JSON}" analyzer name)
  if(NOT ANALYZER_NAME STREQUAL "openpulse-analyzer")
    message(FATAL_ERROR "analyzer.name is ${ANALYZER_NAME}")
  endif()
  string(JSON ROOT GET "${REPORT_JSON}" repository root)
  if(NOT ROOT STREQUAL ".")
    message(FATAL_ERROR "repository.root is ${ROOT}, expected .")
  endif()
  string(JSON ABS_PATH ERROR_VARIABLE ABS_ERR GET "${REPORT_JSON}" repository path)
  if(NOT ABS_ERR)
    message(FATAL_ERROR "v2 repository must not contain a machine path")
  endif()

  if(STATUS STREQUAL "SUCCESS" OR STATUS STREQUAL "PARTIAL_SUCCESS")
    foreach(KEY summary languages structure)
      string(JSON _VALUE ERROR_VARIABLE _ERR GET "${REPORT_JSON}" ${KEY})
      if(_ERR)
        message(FATAL_ERROR "${STATUS} report missing key ${KEY}: ${_ERR}")
      endif()
    endforeach()
  endif()
  if(STATUS STREQUAL "SUCCESS")
    string(JSON REVIEW GET "${REPORT_JSON}" reviewability)
    if(NOT REVIEW STREQUAL "COMPLETE")
      message(FATAL_ERROR "SUCCESS report reviewability is ${REVIEW}")
    endif()
    string(JSON NLIM LENGTH "${REPORT_JSON}" limitations)
    if(NOT NLIM EQUAL 0)
      message(FATAL_ERROR "SUCCESS report has ${NLIM} limitations")
    endif()
  endif()
  if(STATUS STREQUAL "FAILED")
    string(JSON REVIEW GET "${REPORT_JSON}" reviewability)
    if(NOT REVIEW STREQUAL "NOT_USABLE")
      message(FATAL_ERROR "FAILED report reviewability is ${REVIEW}")
    endif()
    foreach(KEY summary languages structure)
      string(JSON _VALUE ERROR_VARIABLE _ERR GET "${REPORT_JSON}" ${KEY})
      if(NOT _ERR)
        message(FATAL_ERROR "FAILED report must not contain ${KEY}")
      endif()
    endforeach()
  endif()
endif()

message(STATUS "report check passed: ${REPORT} (protocol ${PROTOCOL}, status ${STATUS})")
